# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  # 不管上传哪个分支都会促发工作流
  push:
    branches:
      - "*"

#选择maven项目自动生成的
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    #变量
    env:
      DB_DATABASE: renren_fast
      DB_USER: root
      DB_PASSWORD: root

    #redis docker容器  如果项目中用不到redis的话就不用这个
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379

    #从github上拉取代码 并且启动mysql
    steps:
    - uses: actions/checkout@v3
    - name: Set up MySQL
      run: |
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
        mysql -e 'SHOW DATABASES;' -uroot -proot
        mysql -uroot -proot renren_fast < ./db/mysql.sql
        mysql -e 'use renren_fast;show tables;' -uroot -proot

    #在虚拟机上（ubuntu-latest）安装java环境
    - uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven

    #maven打包 测试
    - name: maven打包 测试
      run: mvn --batch-mode --update-snapshots verify
    - run: mkdir staging && cp target/*.jar staging
    - uses: actions/upload-artifact@v3
      with:
        name: Package
        path: staging

    #发送邮件功能   在github上 创建 EMAIL_USERNAME EMAIL_PASSWORD 变量
    - name: 发送邮件
      uses: dawidd6/action-send-mail@v3.6.1
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        # email subject
        subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
        # email body as text
        body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
        # 要发送的邮件 多个逗号分离
        to: contact@xfuture.cc
        # from email name
        from: xFuture

#      部署到测试服务器 有服务器了再测试
#      - name: Deploy to server
#        uses: appleboy/scp-action@master
#        with:
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.USERNAME }}
#          port: 22
#          password: $
#          source: "/staging/Package.jar"
#          target: "/root/"
#          strip_components: 2

#      通过ssh给服务器发送命令重启jar包
#      - name: ls -a via ssh
#        uses: fifsky/ssh-action@master
#        with:
#          command: |
#            cd /tmp
#            ls -a
#          host: ${{ secrets.HOST }}
#          user: root
#          key: ${{ secrets.PRIVATE_KEY}}
